orbs:
  ruby: circleci/ruby@1.4.0
  
version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: java -v


workflows:
    version: 2.1
    build:
        jobs:
        - trial